### ISSUE TITLE
how to fix code style with jscs?

### ISSUE THREAD

**Issue by veggiemonk** [Microsoft/vscode-jscs#10]
It would be so awesome if we could format the code in one command:
http://jscs.info/overview#cli
See option --fix

**Comment by nickbenes** [comment]
+1

**Comment by andersrydman** [comment]
+1 
I noticed that there was a commented out command in extension.ts regarding this. Would be a great feature.

**Comment by zolrath** [comment]
I would love --fix integration along with the ability to --fix on save!

**Comment by fifafu** [comment]
+1 that'd be awesome!

**Comment by cschaba** [comment]
+1

**Comment by egamma** [comment]
This has been added to vscode-eslint and there is a PR for vscode-tslint. So there is are sources of inspiration for a PR 😄

**Comment by mjbvz** [comment]
Closing since we are deprecating this extension (#27) and do not plan any further fixes
