### ISSUE TITLE
unable to build and debug

### ISSUE THREAD

**Issue by SpaceShot** [Microsoft/vscode-jscs#11]
I grabbed the code yesterday (3/14) and following the instructions, could not get the project to build or run.

One issue was VSCode complaining it wanted an absolute path for outDir in launch.json.  I eventually discovered TypeScript was not installed for the client and it was hanging on that compilation.

I noticed this project mimics the "language server" sample and that was a  big help to determining what was wrong.

PR incoming.  I think I have it but am going to test pulling fresh and seeing if I've got it.

**Comment by chrisdias** [comment]
fixed with #12
