### ISSUE TITLE
Alternative location of .jscsrc file

### ISSUE THREAD

**Issue by wvankuipers** [Microsoft/vscode-jscs#15]
It would be nice if we could define a custom location of the `.jscsrc` file. If the file is not in the root of a project the linter will not pick it up.

the jshint linter has this fixed like this:

```
 "jshint.options" : { "config" : "path/to/.jshintrc" }
```

Would it be possible to do the same for this linter?

**Comment by engyii** [comment]
Same request for me. A workspace root is not necessarily the root of the javascript part.

**Comment by mjbvz** [comment]
Closing since we are deprecating this extension (#27) and do not plan any further fixes
