### ISSUE TITLE
Bump version so config fix updates

### ISSUE THREAD

**Issue by pip-pipkin** [Microsoft/vscode-jscs#16]
It looks like there was a fix that was merged in about a month ago that fixes the VSCode settings.json warning for "jscs.configuration". However it looks like this fix was never pushed to Microsoft's extension library to update the warning on the users end. I suspect this is because the version wasn't bumped so VSCode doesn't know there's a new version.

Does the version need to be bumped in the package.json file so VSCode knows there is a new version?

**Comment by mjbvz** [comment]
Closing since we are deprecating this extension #27 and do not plan any further fixes
