### ISSUE TITLE
JSCS should clear errors if a file gets closed 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-jscs#17]
We removed some bogus code in 1.3.x from the core which cleared markers on buffer close. We had to remove that to get to a consistent project build story. No the producer of markers must ensure to clear them if not needed anymore.

If you don't do anything fancy you can use the following snippet:
// Clear diagnostics on close.
documents.onDidClose((event) => {
connection.sendDiagnostics({ uri: event.document.uri, diagnostics: [] });
});

**Comment by mjbvz** [comment]
Closing since we are deprecating this extension (#27) and do not plan any further fixes
