### ISSUE TITLE
JSON schema support for .jscsrc

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-jscs#2]
From @scottaddie on November 22, 2015 4:23

Prior to the 0.10.1 release, the following settings were baked into the editor:

```
    // Control whether jshint is enabled for JavaScript files or not.
"jshint.enable": true,

// The jshint options object to provide args to the jshint command.
"jshint.options": {},
```

Now that there's an official JSHint extension, the following schema support should be added by it rather than including it into the editor:

```
    {
        "fileMatch": [
            "/.jshintrc"
        ],
        "url": "http://json.schemastore.org/jshintrc"
    },
```

I'd argue the same point regarding the JSCS extension. It should add the following to the settings, rather than baking it into the editor:

```
    {
        "fileMatch": [
            "/.jscsrc"
        ],
        "url": "http://json.schemastore.org/jscsrc"
    }
```

Copied from original issue: Microsoft/vscode#433

**Comment by chrisdias** [comment]
thanks @scottaddie !
