### ISSUE TITLE
JSCS running in git files

### ISSUE THREAD

**Issue by carlfranz** [Microsoft/vscode-jscs#20]
When comparing with an old version of file in the git repository, jscs run on that file. 

![screenshot 2017-06-19 12 17 54](https://user-images.githubusercontent.com/10374558/27280787-825dbfc0-54e9-11e7-8288-434ad5fad2ba.png)

**Comment by rogeriorc** [comment]
Same with SVN (https://github.com/JohnstonCode/svn-scm)

![image](https://user-images.githubusercontent.com/2599798/37371036-d4c1080a-26ec-11e8-9f97-090028958bde.png)

**Comment by mjbvz** [comment]
Closing since we are deprecating this extension (#27) and do not plan any further fixes
