### ISSUE TITLE
Allow locally stored preset paths

### ISSUE THREAD

**Issue by andreszorro** [Microsoft/vscode-jscs#21]
As I was looking at the source code, seems like the only configuration options are the ones listed here: https://github.com/Microsoft/vscode-jscs/blob/e94f387d8fa56d90386974cd84bd650ff986c64c/jscs/package.json#L45, but jscs has the ability to use presets stored in local files. The problem is that vscode-jscs stops working if the preset property isn't one of those strings.

Is there a way to allow any string as part of these config validation rules?

**Comment by mjbvz** [comment]
Closing since we are deprecating this extension (#27) and do not plan any further fixes
