### ISSUE TITLE
How its work?

### ISSUE THREAD

**Issue by the-evgenii** [Microsoft/vscode-jscs#3]
I have installed jscs
![image](https://cloud.githubusercontent.com/assets/7571432/11337254/a7a01258-91fc-11e5-8a43-a291e11f6bbf.png)
And jscs for vscode.

My .jscsrc in project root

```
{
  "preset": "google",
  "esnext": true,
  "fileExtensions": [
    ".js",
    ".jsx"
  ],
  "requireSemicolons": true,
  "requireParenthesesAroundIIFE": true,
  "maximumLineLength": 120,
  "validateLineBreaks": "LF",
  "validateIndentation": 2,
  "disallowTrailingComma": true,
  "disallowUnusedParams": true,
  "disallowSpacesInsideObjectBrackets": null,
  "disallowImplicitTypeConversion": [
    "string"
  ],
  "safeContextKeyword": "_this",
  "jsDoc": {
    "checkAnnotations": "closurecompiler",
    "checkParamNames": true,
    "requireParamTypes": true,
    "checkRedundantParams": true,
    "checkReturnTypes": true,
    "checkRedundantReturns": true,
    "requireReturnTypes": true,
    "checkTypes": "capitalizedNativeCase",
    "checkRedundantAccess": true,
    "requireNewlineAfterDescription": true
  },
  "excludeFiles": [
    ".meteor/*"
  ]
}
```

But vscode did not lint jsx and js files

**Comment by janpieterz** [comment]
Same here, installed globally, installed in vs code. It works in Atom (with the jscs extension) but not in vs code, leading me to believe it has something to do with the config or the extension.

Made sure that the setting is enabled (somehow after installing it defaults to false, which seems a bit odd) and both in my userspace + my workspace the following config is present:

``` js
{
    "jscs.enable":true
}
```

**Comment by rafaelaudy** [comment]
:+1: Same here!

**Comment by the-evgenii** [comment]
This package really not working with .jscsrc in my project root folder

```
{
  "preset": "google",
  "esnext": true,
  "maximumLineLength": 120,
  "validateLineBreaks": "LF",
  "fileExtensions": [
    ".js", ".jsx"
  ]
}
```

Only work fine with settings.json

```
"jscs.enable": true,
"jscs.preset": "google"
```

**Comment by xak2000** [comment]
Why it is not enabled by default after install? Why is `"jscs.enable": false` in default config?
I thought it didn't work until I checked the configuration.

**Comment by egamma** [comment]
@chrisdias To be consistent with eslint, jshint, tsling the enablement configuration `jscs.enable` should be `true` by default (something which was changed before the beta).
