### ISSUE TITLE
Airbnb preset is not defined and throws a warning

### ISSUE THREAD

**Issue by janpieterz** [Microsoft/vscode-jscs#4]
The airbnb preset in the .jscsrc file throws a warning and hints at only allowing jquery and google, while the extensions documentation suggest otherwise.

![image](https://cloud.githubusercontent.com/assets/383634/11400848/dfdc6236-938f-11e5-8c4a-03276eb5156a.png)

**Comment by chrisdias** [comment]
Made a pull request on the schema store: https://github.com/SchemaStore/schemastore/pull/59
