### ISSUE TITLE
"excludeFiles" setting is not respected

### ISSUE THREAD

**Issue by marinabilles** [Microsoft/vscode-jscs#8]
The addon does not respect the "excludeFiles" property in `.jscsrc` (also not when put in jscs.configuration object in `settings.json`):

``` json
"excludeFiles": ["data/**"]
```

If a file in the data/ folder is passed to the `jscs` command line tool, no errors appear.

If the file is opened in Visual Studio Code, jscs errors are shown. Similarly if individual files are excluded in "excludeFiles".

**Comment by SpaceShot** [comment]
I wanted to try to figure this out but I can't seem to get the extension in the debugger.  Following the instructions left me with a message:
Activating extension `ms-vscode.jscs` failed:  Cannot find module 'c:/Source/vscode-jscs/jscs/out/extension'

**Comment by SpaceShot** [comment]
Opened Issue #11 to address the build problems.  After I'd like to check out this issue.

**Comment by murphmar** [comment]
+1

**Comment by Tenemo** [comment]
+1, still an issue, really annoying with _node_modules_ being included as well as all of my _.min.js_ files.

**Comment by mjbvz** [comment]
Closing since we are deprecating this extension (#27) and do not plan any further fixes
