### ISSUE TITLE
not properly setting up License in package.json

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-jscs#9]
when clicking on "LICENSE" in VS Code from the command palette we're going to an empty page in the Marketplace. Need to figure out what I'm doing wrong...

**Comment by chrisdias** [comment]
doc: https://docs.npmjs.com/files/package.json#license
example: https://marketplace.visualstudio.com/items/msjsdiag.debugger-for-chrome/license

``` json
license: "SEE LICENSE IN LICENSE"
```

**Comment by egamma** [comment]
@chrisdias there was a bug in `vsce` where the `license.txt` file didn't get published.  I suggest to update `vsce` and to rename `license.md` to `license.txt`.

**Comment by chrisdias** [comment]
I fixed this a while back, should have closed this.  the license is properly published to https://marketplace.visualstudio.com/items/ms-vscode.jscs/license and is in the distro.
